### ISSUE TITLE
Add severity to Rules

### ISSUE THREAD

**Issue by rrrene** [lpil/dogma#109]
@meadsteve correctly pointed out that we might different kinds of rules. Some that try to enforce the elixir-community coding style which are basically for accessibility+readability of the code (like `LineLength`) and others, which are trying to enforce best practices to avoid pitfalls later in the code's life cycle (like `CyclomaticComplexity`).

I would propose to add a function to each rule called severity that is either `style` or `warning` (for the lack of a better term to express that these "warn" the user of a possible burden in the future).

We could think up different implementations for this like a macro or module attribute, but I would think that in the spirit of "explicit over explicit" we should just go with a function returning a String/Binary.

``` elixir
defmodule Dogma.Rules.LineLength do
  @behaviour Dogma.Rule

  def severity, do: "style"                         # <-------------

  def test(script), do: test(script, [])

  # [...]
end
```

Any ideas? Maybe someone finds better phrasings for `severity`, `style`, and/or `warning`?

**Comment by lpil** [comment]
I think it would be nice that if we had this feature, the severity was set by the ruleset rather than the rule, so it can be customised easily depending on the situation.

**Comment by 5thWall** [comment]
I think `severity` is the wrong label for what we're doing, as is `warning`. Let the compiler handle errors and warnings. We just have different categories of rules.

I think that the category is inherent to the rule, so I don't think they should be defined by rule sets. Instead of a function on the rule defining its category I think we should follow [rubocop's example](https://github.com/bbatsov/rubocop/tree/master/lib/rubocop/cop) and have modules representing categories. So we could have `Dogma.Rules.Metrics.LineLength` and `Dogma.Rules.Lint.ComparisonToBoolean`.

If we do want a severity on our rules, then I agree that it should be set by a ruleset so it can be customized. And I would add that the severity should be meaningful, like if I have two rulessets with severe violations and less severe ones, it would be nice if dogma would print all violations, but only return an error code if there's a severe violation.

The reason for this is that I like to have a linter run before commits in a git hook. Ideally it would warn me about less severe rules, and only block me from committing if my code has something really stupid in it.

**Comment by lpil** [comment]
I think I agree about it being the wrong label.

Perhaps it could just a flag which dictates whether the application will exit with 0 or not if this rule fails.

**Comment by rrrene** [comment]
@5thWall `category` is a much better term for what I wanted to express, thx! (not a native speaker). I am in complete agreement with your other points.

@lpil I am wondering if the "failing *hard* when the rule fails" is more of an configuration option (with sensible defaults, naturally)? I could imagine both scenarios, but am wondering which route we want to go:

- Rules define whether or not they cause the Mix task to exit with an exit code other than zero.
- We have a configuation option which Rules/RuleSet can cause the Mix task to fail this way.
