### ISSUE TITLE
Move away from passing in "formatter" modules to callbacks, genevents, or similar.

### ISSUE THREAD

**Issue by lpil** [lpil/dogma#143]
We should pass in callback functions rather than a formatter module in order to react to the results of tests.

As suggested in #129

**Comment by 5thWall** [comment]
What do you think about, instead of callbacks, using `GenEvent` and having the formatter modules subscribe to that instead. It gives us the same dependency inversion as passing in a callback function, while still keeping the full lifecycle of different outputs compartmentalized in individual modules.

**Comment by lpil** [comment]
That actually looks very nice. I've not really delved into OTP yet, so I wasn't aware that this was a thing.

If you could open that pull request, that would be fantastic. I do have some feedback that I'd like to run by you :)

Thanks Andy!
