### ISSUE TITLE
Create an easily installable binary to go in $PATH

### ISSUE THREAD

**Issue by lpil** [lpil/dogma#18]
Is it possible to have a hex package install and add a binary to $PATH?

Hell, is it possible to easily install a hex package outside of a mix project?

**Comment by 5thWall** [comment]
So far I've only found two ways to go about this. The user can install dogma as a mix archive, or we can provide a non-mix command line program that the user installs as an escript.

## Mix Archive

The user would install by downloading the repository and then running:
```
mix deps.get
MIX_ENV=prod mix archive.build
mix archive.install
```

Afterwards the user could run `mix dogma` anywhere. The main problem I see with this approach is that as far as I can tell the installed archive takes precedence over a local dependency. Meaning the user would have to choose between having it installed globally or being able to use different versions per project.

## Escript

The user would install by downloading the repository and then running:

```
mix deps.get
mix escript.build
```

And then moving the built escript to their path. Then the user would have `dogma` as a command on their system.

This could turn into a hybrid solution. Have a global `dogma` on the system, and then allow the user to include dogma as a dependency and have `mix dogma` installed per-project.

There was a [thread on the Elixir-lang group talking about adding a `mix escript.install` command](https://groups.google.com/forum/#!topic/elixir-lang-core/LEr5Vjd1gys) which would even be able to fetch and install escripts from https://hex.pm, but I haven't found anything more on that, and it's not currently in the Elixir-Lang issue tracker. Still, escripts might be well supported in the future.

Personally I like the hybrid approach. I'd like to have dogma installed to check scripts I build outside of a mix project. But I can also see how it would be useful for projects to include it as a dependency so contributors would just need to run `mix dogma` instead of needing to go through the process of installing it globally.

**Comment by lpil** [comment]
The other question here is how do we manage configuration with an instance of Dogma that is not tied to a particular mix project.

**Comment by 5thWall** [comment]
We should be able to read in an Elixir config file using `Mix.Config.read!`. 

Then the question is where is this file located. I'd suggest these locations in this order:
* File passed in with `--config`
* `config/dogma.exs`
* `./dogma.exs`

Maybe not the command line option for v1, but at least `config/dogma.exs` and `./dogma.exs`.

**Comment by lpil** [comment]
Perhaps we want a global one too. `~/.dogma.exs` ?

**Comment by lpil** [comment]
> There was a thread on the Elixir-lang group talking about adding a mix escript.install command which would even be able to fetch and install escripts from https://hex.pm, but I haven't found anything more on that, and it's not currently in the Elixir-Lang issue tracker.

Could you open one please?

**Comment by 5thWall** [comment]
According to the contributor doc, they like questions like this in the language talk group. https://groups.google.com/forum/#!topic/elixir-lang-talk/39Z0iH-5Jyw

**Comment by 5thWall** [comment]
So, there is a pull request related to installing escripts with mix: https://github.com/elixir-lang/elixir/pull/2974

According to José, he want's to put it on track after 1.1 and 1.2.

**Comment by alco** [comment]
Hi,

I saw a reference to this thread from the Elixir PR mentioned in the previous comment and thought I'd chime in.

Currently, the most viable way to provide an Elixir tool that integrates with Mix is via a custom Mix task added as a dependency to the target project. That's how most of 3rd party tools work: `mix dialyze`, `mix docs`, `mix release`, and others.

While creating an archive may look like a convenient way to install a custom Mix task globally (i.e. not tied to a single project via its deps), it causes more problems in the long term. Some of the problems people may encounter:

  * Mismatch between the version of Elixir a user has installed and the version a Dogma archive expects. This may cause different kinds of failures when using the archive. For example, Elixir 1.2 adds `with` as a keyword, and depending on the implementation details of Dogma it may either ignore it, or crash, or work incorrectly when it encounters it in the code.

  * There is also a problem when a user accidentally installs an archive and also adds Dogma as a dependency to a project. The user may end up running two different versions, and either of them may override the other within the project, depending on subtle details.

Using the project as a dependency will be more manageable for the end user. There's no silver bullet solution to the problem of a an unexpected version of Elixir, especially for a source-level tool like Dogma, but there's at least a way to work around it: set a strict Elixir version requirement in Dogma so that the end user will get a warning when they upgrade their Elixir.

**Comment by alco** [comment]
And as for escripts, those are best used for tools that don't need to go looking into a Mix project's config or source code, but rather have a self-contained purpose. For example, a simple web server or a proxy could be distributed as an escript.

**Comment by lpil** [comment]
Hi Alexei, thanks for your post. Very informative, and reenforces what I've been thinking lately.

I've been leaning towards keeping it just a mix dep, people can use credo if they want something isolated from the project.

RE different Elixir versions, I'm hoping we'll be able to support all current versions of Elixir, and we've managed to do so this far, but I expect this will become tricker over time. I'm aware there are lots of edge cases that we don't handle appropriately that can cause Dogma to crash, but I've unfortunately not had the time to resolve these issues.

**Comment by alco** [comment]
No problem. I also forgot to mention probably the biggest inconvenience of archives: they don't support dependencies. So when you do `mix archive.build` in your Mix project, it only packages your project's modules into the resulting archives. Needless to say, it won't work if your project relies on any dependencies.

**Comment by lpil** [comment]
Ah, I didn't know that. Thank you.

**Comment by develop7** [comment]
> I've been leaning towards keeping it just a mix dep, people can use credo if they want something isolated from the project.

@lpil I've just tried add dogma to a project that already got `poison` v2.x installed, and failed to `mix deps.get`, since dogma's JSON reporter depends on `poison` v1.x. So, unless you are going to split reporters (or just json reporter) out of dogma, I'm leaning towards standalone escript executable (seems like only way to go).

**Comment by lpil** [comment]
I think I'd like to remove that dep and move it to a plugin. I'll make it an open ended dep for now.

**Comment by lpil** [comment]
@develop7 I've released a new version that should help. :)

**Comment by develop7** [comment]
@lpil thanks!
